spring:
  # mysql 数据库配置 47.96.153.185  127.0.0.1
  datasource:
    url: jdbc:mysql://47.96.153.185:3306/db_blog?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lyq@qq.com
    hikari:
      minimum-idle: 10
      maximum-pool-size: 60
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  #  redis相关配置 47.96.153.185 127.0.0.1
  redis:
    host: 47.96.153.185
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: PT10s
        max-idle: 30
        min-idle: 1
      lettuce:
        shutdown-timeout: PT10s
  # 文件上传大小配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  # fastdfs 配置
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 47.96.153.185 :22122
upload:
  base-url: http://47.96.153.185/
  allow-types:
    - image/jpeg
    - image/jpg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg